/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyChildComponent {
    'titlePasswordComponent': string;
  }
  interface MyChildComponentAttributes extends StencilHTMLAttributes {
    'onOnClickEmitter'?: (event: CustomEvent) => void;
    'titlePasswordComponent'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'onOnEvent'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyChildComponent': Components.MyChildComponent;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-child-component': Components.MyChildComponentAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyChildComponentElement extends Components.MyChildComponent, HTMLStencilElement {}
  var HTMLMyChildComponentElement: {
    prototype: HTMLMyChildComponentElement;
    new (): HTMLMyChildComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-child-component': HTMLMyChildComponentElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-child-component': HTMLMyChildComponentElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
